const seedVehicles = [
  {
    brand: 'Tata',
    model: 'Nexon',
    category: 'Car',
    bodyType: 'SUV',
    variantSummary: 'Smart | Petrol',
    priceFrom: 8.69,
    priceTo: 16.78,
    priceDisplay: '₹ 8.69 - 16.78 Lakh*',
    fuelType: 'Petrol / CNG / Diesel',
    transmission: 'Manual / Automatic',
    engine: '1.2L Turbo Petrol',
    engineCC: 1199,
    power: '118.27 bhp',
    torque: '170 Nm',
    mileage: '17.0 kmpl',
    mileageValue: 17.0,
    driveType: 'FWD',
    groundClearance: 208,
    seatingCapacity: 5,
    bootSpace: 382,
    seatHeight: 0,
    kerbWeight: 1255,
    length: 3995,
    width: 1804,
    height: 1620,
    wheelbase: 2498,
    turningRadius: 5.1,
    cabinHeadroom: 985,
    driverSeatHeightRange: { min: 580, max: 640 },
    roofHeight: 1620,
    steeringType: 'EPS',
    easeOfDriving: 'Easy',
    parkingDifficulty: 'Easy',
    idealHeightMin: 155,
    idealHeightMax: 190,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 5,
    safetyAgency: 'Global NCAP Rating',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
    description: 'India’s highest rated compact SUV known for unmatched structural safety, high ground clearance, and punchy turbo performance.',
    baseScores: {
      safety: 9,
      groundClearance: 9,
      comfort: 8,
      spacePracticality: 8,
      mileageRunningCost: 6,
      maintenanceCost: 7,
      performance: 8,
      resaleValue: 7,
      highwayStability: 9,
      cityDriveSuitability: 8,
      ergonomicFit: 9,
      handleability: 8,
    },
    highlightBadges: ['5-Star Safety', '208mm Ground Clearance', 'Punchy Turbo'],
    inherentStrengths: [
      'Excellent ground clearance suitable for Indian roads',
      'Very good highway stability and driving confidence',
      'Strong safety features with high Global NCAP rating',
      'Spacious cabin and comfortable for family use',
    ],
    inherentConsiderations: [
      'Mileage is average in city traffic',
      'Turbo engine requires regular maintenance',
      'Boot space is moderate for long trips',
      'Rear seat comfort could be better for 3 adults',
    ],
    isActive: true,
  },
  {
    brand: 'Mahindra',
    model: 'Thar',
    category: 'Car',
    bodyType: 'SUV',
    variantSummary: 'AX Opt / LX | 4x4 / RWD',
    priceFrom: 11.35,
    priceTo: 17.60,
    priceDisplay: '₹ 11.35 - 17.60 Lakh*',
    fuelType: 'Petrol / Diesel',
    transmission: 'Manual / Automatic',
    engine: '2.0L mStallion Turbo Petrol',
    engineCC: 1997,
    power: '150 bhp',
    torque: '320 Nm',
    mileage: '12.0 kmpl',
    mileageValue: 12.0,
    driveType: '4WD',
    groundClearance: 226,
    seatingCapacity: 4,
    bootSpace: 150,
    seatHeight: 0,
    kerbWeight: 1750,
    length: 3985,
    width: 1820,
    height: 1844,
    wheelbase: 2450,
    turningRadius: 5.8,
    cabinHeadroom: 1040,
    driverSeatHeightRange: { min: 680, max: 740 },
    roofHeight: 1844,
    steeringType: 'Hydraulic',
    easeOfDriving: 'Demanding',
    parkingDifficulty: 'Moderate',
    idealHeightMin: 165,
    idealHeightMax: 198,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 4,
    safetyAgency: 'Global NCAP Rating',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80',
    description: 'Iconic lifestyle off-roader with class-leading 4x4 capability, high road presence, and rugged all-terrain conquerability.',
    baseScores: {
      safety: 8,
      groundClearance: 10,
      comfort: 5,
      spacePracticality: 4,
      mileageRunningCost: 4,
      maintenanceCost: 6,
      performance: 9,
      resaleValue: 9,
      highwayStability: 6,
      cityDriveSuitability: 6,
      ergonomicFit: 7,
      handleability: 4,
    },
    highlightBadges: ['Iconic 4x4 Off-roader', '226mm Clearance', 'Tremendous Resale'],
    inherentStrengths: [
      'Best-in-class off-road capability and water wading',
      'Massive 226mm ground clearance tackles any rough terrain',
      'Powerful mStallion / mHawk engines with rapid acceleration',
      'High resale value and massive road presence',
    ],
    inherentConsiderations: [
      'Requires experienced handling with heavier steering and firm ladder chassis',
      'Rear seat access is cramped and boot space is very limited (150L)',
      'High running cost due to low fuel economy in heavy traffic',
      'Not ideal for elderly passengers getting in and out due to tall ingress',
    ],
    isActive: true,
  },
  {
    brand: 'Hyundai',
    model: 'Creta',
    category: 'Car',
    bodyType: 'SUV',
    variantSummary: 'SX / SX(O) | Petrol / Diesel',
    priceFrom: 10.99,
    priceTo: 20.15,
    priceDisplay: '₹ 10.99 - 20.15 Lakh*',
    fuelType: 'Petrol / Diesel',
    transmission: 'Manual / IVT / DCT',
    engine: '1.5L MPi / 1.5L Turbo Petrol',
    engineCC: 1497,
    power: '113.18 bhp',
    torque: '143.8 Nm',
    mileage: '17.4 kmpl',
    mileageValue: 17.4,
    driveType: 'FWD',
    groundClearance: 190,
    seatingCapacity: 5,
    bootSpace: 433,
    seatHeight: 0,
    kerbWeight: 1260,
    length: 4330,
    width: 1790,
    height: 1635,
    wheelbase: 2610,
    turningRadius: 5.3,
    cabinHeadroom: 990,
    driverSeatHeightRange: { min: 570, max: 630 },
    roofHeight: 1635,
    steeringType: 'EPS',
    easeOfDriving: 'Very Easy',
    parkingDifficulty: 'Easy',
    idealHeightMin: 152,
    idealHeightMax: 192,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 5,
    safetyAgency: 'Bharat NCAP Rating',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80',
    description: 'India’s benchmark mid-size SUV offering supreme cabin refinement, panoramic sunroof, Level 2 ADAS, and smooth city driving.',
    baseScores: {
      safety: 8,
      groundClearance: 8,
      comfort: 9,
      spacePracticality: 9,
      mileageRunningCost: 7,
      maintenanceCost: 7,
      performance: 8,
      resaleValue: 9,
      highwayStability: 8,
      cityDriveSuitability: 9,
      ergonomicFit: 9,
      handleability: 9,
    },
    highlightBadges: ['Benchmark Comfort', 'High Resale', '433L Boot Space'],
    inherentStrengths: [
      'Extremely refined engine and plush suspension ride quality',
      'Generous rear legroom and large 433-litre family boot space',
      'Wide service network and strong resale market value',
      'Effortless light steering makes it easy in city congestion',
    ],
    inherentConsiderations: [
      'Top-end variants touch over ₹20 Lakh price bracket',
      'Turbo petrol variant is sensitive to heavy throttle driving',
      'Ground clearance (190mm) is lower than hardcore 4x4s',
    ],
    isActive: true,
  },
  {
    brand: 'Maruti Suzuki',
    model: 'Grand Vitara',
    category: 'Car',
    bodyType: 'SUV',
    variantSummary: 'Delta / Alpha+ | Strong Hybrid',
    priceFrom: 10.80,
    priceTo: 20.09,
    priceDisplay: '₹ 10.80 - 20.09 Lakh*',
    fuelType: 'Petrol / Strong Hybrid / CNG',
    transmission: 'Manual / Automatic / e-CVT',
    engine: '1.5L Intelligent Electric Hybrid',
    engineCC: 1490,
    power: '114.4 bhp',
    torque: '141 Nm',
    mileage: '27.97 kmpl',
    mileageValue: 27.97,
    driveType: 'FWD',
    groundClearance: 210,
    seatingCapacity: 5,
    bootSpace: 373,
    seatHeight: 0,
    kerbWeight: 1295,
    length: 4345,
    width: 1795,
    height: 1645,
    wheelbase: 2600,
    turningRadius: 5.4,
    cabinHeadroom: 980,
    driverSeatHeightRange: { min: 570, max: 630 },
    roofHeight: 1645,
    steeringType: 'EPS',
    easeOfDriving: 'Very Easy',
    parkingDifficulty: 'Easy',
    idealHeightMin: 152,
    idealHeightMax: 190,
    batteryCapacity: '0.76 kWh (Self-Charging)',
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 4,
    safetyAgency: 'Global NCAP Rating',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=900&q=80',
    description: 'Market-leading fuel efficiency with intelligent self-charging hybrid technology, low maintenance costs, and 210mm ground clearance.',
    baseScores: {
      safety: 7,
      groundClearance: 9,
      comfort: 8,
      spacePracticality: 7,
      mileageRunningCost: 10,
      maintenanceCost: 9,
      performance: 7,
      resaleValue: 9,
      highwayStability: 8,
      cityDriveSuitability: 9,
      ergonomicFit: 8,
      handleability: 9,
    },
    highlightBadges: ['27.97 kmpl Mileage', 'Lowest Running Cost', 'Maruti Reliability'],
    inherentStrengths: [
      'Phenomenal real-world fuel economy (27.97 kmpl) saves huge running costs without plug-in charging',
      'Very affordable long-term maintenance and parts availability',
      'Generous 210mm ground clearance tackles high speedbreakers effortlessly',
      'EV mode enables whisper-quiet, smooth crawling in stop-and-go traffic',
    ],
    inherentConsiderations: [
      'Strong Hybrid battery pack occupies portion of luggage space (255L in hybrid)',
      'Engine gets vocal when accelerating hard on open highways',
      'Interior plastics feel utilitarian compared to luxury rivals',
    ],
    isActive: true,
  },
  {
    brand: 'Honda',
    model: 'City',
    category: 'Car',
    bodyType: 'Sedan',
    variantSummary: 'V / VX / ZX | i-VTEC',
    priceFrom: 12.08,
    priceTo: 16.35,
    priceDisplay: '₹ 12.08 - 16.35 Lakh*',
    fuelType: 'Petrol / Strong Hybrid',
    transmission: '6-Speed MT / CVT',
    engine: '1.5L i-VTEC DOHC',
    engineCC: 1498,
    power: '119.35 bhp',
    torque: '145 Nm',
    mileage: '18.4 kmpl',
    mileageValue: 18.4,
    driveType: 'FWD',
    groundClearance: 165,
    seatingCapacity: 5,
    bootSpace: 506,
    seatHeight: 0,
    kerbWeight: 1150,
    length: 4574,
    width: 1748,
    height: 1489,
    wheelbase: 2600,
    turningRadius: 5.3,
    cabinHeadroom: 940,
    driverSeatHeightRange: { min: 510, max: 560 },
    roofHeight: 1489,
    steeringType: 'EPS',
    easeOfDriving: 'Easy',
    parkingDifficulty: 'Moderate',
    idealHeightMin: 150,
    idealHeightMax: 182,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 5,
    safetyAgency: 'ASEAN NCAP Rating',
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=80',
    description: 'The definitive executive sedan known for sofa-like rear seat comfort, massive 506L boot, high-speed stability, and responsive i-VTEC engine.',
    baseScores: {
      safety: 8,
      groundClearance: 6,
      comfort: 10,
      spacePracticality: 9,
      mileageRunningCost: 8,
      maintenanceCost: 8,
      performance: 8,
      resaleValue: 8,
      highwayStability: 10,
      cityDriveSuitability: 8,
      ergonomicFit: 7,
      handleability: 8,
    },
    highlightBadges: ['Supreme Sedan Comfort', '506L Boot Space', 'High-Speed Stability'],
    inherentStrengths: [
      'Exceptional high-speed highway stability and aerodynamics',
      'Best-in-segment rear-seat comfort with unmatched legroom for passengers',
      'Cavernous 506-litre boot easily swallows 4 full-sized suitcases',
      'Smooth, rev-happy naturally aspirated i-VTEC engine with low maintenance',
    ],
    inherentConsiderations: [
      'Low roofline (1489mm) and seating position may feel cramped for drivers over 6ft',
      'Lower ground clearance (165mm) requires careful crawling over large unpaved potholes',
      'Longer sedan length (4574mm) requires extra care in tight parking basements',
    ],
    isActive: true,
  },
  {
    brand: 'Mahindra',
    model: 'XUV700',
    category: 'Car',
    bodyType: 'SUV',
    variantSummary: 'AX5 / AX7 | 5 & 7 Seater',
    priceFrom: 13.99,
    priceTo: 26.99,
    priceDisplay: '₹ 13.99 - 26.99 Lakh*',
    fuelType: 'Petrol / Diesel',
    transmission: 'Manual / Automatic',
    engine: '2.0L Turbo Petrol / 2.2L mHawk Diesel',
    engineCC: 1997,
    power: '197 bhp',
    torque: '380 Nm',
    mileage: '14.5 kmpl',
    mileageValue: 14.5,
    driveType: 'AWD',
    groundClearance: 200,
    seatingCapacity: 7,
    bootSpace: 450,
    seatHeight: 0,
    kerbWeight: 1960,
    length: 4695,
    width: 1890,
    height: 1755,
    wheelbase: 2750,
    turningRadius: 5.9,
    cabinHeadroom: 1020,
    driverSeatHeightRange: { min: 620, max: 700 },
    roofHeight: 1755,
    steeringType: 'EPS',
    easeOfDriving: 'Moderate',
    parkingDifficulty: 'Difficult',
    idealHeightMin: 160,
    idealHeightMax: 196,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 5,
    safetyAgency: 'Global NCAP Rating',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=80',
    description: 'Feature-loaded 7-seater powerhouse with 197 bhp engine, Level 2 ADAS active safety, and commanding highway dominance.',
    baseScores: {
      safety: 10,
      groundClearance: 8,
      comfort: 9,
      spacePracticality: 10,
      mileageRunningCost: 5,
      maintenanceCost: 6,
      performance: 10,
      resaleValue: 8,
      highwayStability: 10,
      cityDriveSuitability: 6,
      ergonomicFit: 9,
      handleability: 5,
    },
    highlightBadges: ['197 bhp Powerhouse', '5-Star NCAP + ADAS', '7-Seater Family Hauler'],
    inherentStrengths: [
      'Unrivalled 197 bhp highway overtaking acceleration and speed',
      '5-Star Global NCAP safety rating paired with Level 2 ADAS active protection',
      'Versatile 7-seater flexible seating ideal for joint families',
      'Excellent cabin space and headroom for tall drivers and passengers',
    ],
    inherentConsiderations: [
      'Bulky dimensions and 197 bhp power require experienced driver confidence in tight city traffic',
      'High fuel consumption in stop-and-go city traffic (8-10 kmpl petrol)',
      'Difficult to park in narrow residential streets and compact apartment spots',
    ],
    isActive: true,
  },
  {
    brand: 'Tata',
    model: 'Tiago EV',
    category: 'Car',
    bodyType: 'Hatchback',
    variantSummary: 'XT / XZ+ Tech Lux | 24 kWh',
    priceFrom: 7.99,
    priceTo: 11.89,
    priceDisplay: '₹ 7.99 - 11.89 Lakh*',
    fuelType: 'Electric',
    transmission: 'Automatic (Single Speed)',
    engine: 'Permanent Magnet Synchronous Motor',
    engineCC: 0,
    power: '74 bhp',
    torque: '114 Nm',
    mileage: '315 km/charge (ARAI)',
    mileageValue: 24.0,
    driveType: 'FWD',
    groundClearance: 165,
    seatingCapacity: 5,
    bootSpace: 240,
    seatHeight: 0,
    kerbWeight: 1150,
    length: 3769,
    width: 1677,
    height: 1535,
    wheelbase: 2400,
    turningRadius: 4.9,
    cabinHeadroom: 950,
    driverSeatHeightRange: { min: 530, max: 580 },
    roofHeight: 1535,
    steeringType: 'EPS',
    easeOfDriving: 'Very Easy',
    parkingDifficulty: 'Very Easy',
    idealHeightMin: 148,
    idealHeightMax: 182,
    batteryCapacity: '24 kWh IP67 Battery',
    chargingRequired: true,
    homeChargingTime: '8.5 hrs (15A socket)',
    fastChargingSupport: true,
    evRangeReal: 205,
    safetyRating: 4,
    safetyAgency: 'Global NCAP Rating',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=900&q=80',
    description: 'India’s most accessible electric car delivering ₹1/km running cost, compact footprint for effortless city parking, and instant EV torque.',
    baseScores: {
      safety: 8,
      groundClearance: 7,
      comfort: 8,
      spacePracticality: 7,
      mileageRunningCost: 10,
      maintenanceCost: 9,
      performance: 7,
      resaleValue: 7,
      highwayStability: 7,
      cityDriveSuitability: 10,
      ergonomicFit: 8,
      handleability: 10,
    },
    highlightBadges: ['₹1/km Running Cost', 'Effortless City Parking', 'Zero Tailpipe Emissions'],
    inherentStrengths: [
      'Ultra-low running cost (approx ₹1.10 per km with home charging)',
      'Extremely compact footprint with light steering makes city traffic effortless for beginners',
      'Silent, clutchless instant throttle response without gear shifts',
      'Minimal routine servicing required (no engine oil, filters, spark plugs)',
    ],
    inherentConsiderations: [
      'Requires home 15A socket or nearby DC fast charging access for daily ownership',
      'Real-world highway range of ~190-210 km requires planned charging on long road trips',
      'Cabin headroom is tight for drivers taller than 6 feet',
    ],
    isActive: true,
  },
  {
    brand: 'Maruti Suzuki',
    model: 'Alto K10',
    category: 'Car',
    bodyType: 'Hatchback',
    variantSummary: 'LXi / VXi | 1.0L DualJet',
    priceFrom: 3.99,
    priceTo: 5.96,
    priceDisplay: '₹ 3.99 - 5.96 Lakh*',
    fuelType: 'Petrol / CNG',
    transmission: '5-Speed Manual / AGS Automatic',
    engine: '1.0L K10C DualJet Petrol',
    engineCC: 998,
    power: '65.71 bhp',
    torque: '89 Nm',
    mileage: '24.39 kmpl',
    mileageValue: 24.39,
    driveType: 'FWD',
    groundClearance: 167,
    seatingCapacity: 5,
    bootSpace: 214,
    seatHeight: 0,
    kerbWeight: 750,
    length: 3530,
    width: 1490,
    height: 1520,
    wheelbase: 2380,
    turningRadius: 4.5,
    cabinHeadroom: 910,
    driverSeatHeightRange: { min: 510, max: 550 },
    roofHeight: 1520,
    steeringType: 'EPS',
    easeOfDriving: 'Very Easy',
    parkingDifficulty: 'Very Easy',
    idealHeightMin: 145,
    idealHeightMax: 178,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 2,
    safetyAgency: 'Global NCAP Rating',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=900&q=80',
    description: 'India’s favorite entry-level city hatchback with tight 4.5m turning radius, peppy 1.0L engine, and effortless narrow street parking.',
    baseScores: {
      safety: 4,
      groundClearance: 7,
      comfort: 6,
      spacePracticality: 6,
      mileageRunningCost: 10,
      maintenanceCost: 10,
      performance: 6,
      resaleValue: 9,
      highwayStability: 5,
      cityDriveSuitability: 10,
      ergonomicFit: 5,
      handleability: 10,
    },
    highlightBadges: ['₹3.99L Entry Price', '4.5m Turning Radius', '24.39 kmpl Mileage'],
    inherentStrengths: [
      'Ultra-compact dimensions (3.53m) squeeze into the tightest alleyways and parking spots',
      'Extremely light 750kg weight and peppy K10C engine make city commuting effortless for beginners',
      'Pocket-friendly maintenance and massive Maruti spare parts availability across India',
    ],
    inherentConsiderations: [
      'Compact cabin with low headroom feels cramped for drivers 6ft and taller',
      'Lightweight build has low structural safety rating (2-Star Global NCAP)',
      'Highway stability is modest above 80 km/h and sensitive to crosswinds',
    ],
    isActive: true,
  },
  {
    brand: 'Maruti Suzuki',
    model: 'WagonR',
    category: 'Car',
    bodyType: 'Hatchback',
    variantSummary: 'VXi / ZXi | 1.2L DualJet',
    priceFrom: 5.54,
    priceTo: 7.38,
    priceDisplay: '₹ 5.54 - 7.38 Lakh*',
    fuelType: 'Petrol / CNG',
    transmission: '5-Speed Manual / AGS Automatic',
    engine: '1.2L K12N DualJet Petrol',
    engineCC: 1197,
    power: '88.5 bhp',
    torque: '113 Nm',
    mileage: '23.56 kmpl',
    mileageValue: 23.56,
    driveType: 'FWD',
    groundClearance: 170,
    seatingCapacity: 5,
    bootSpace: 341,
    seatHeight: 0,
    kerbWeight: 835,
    length: 3655,
    width: 1620,
    height: 1675,
    wheelbase: 2435,
    turningRadius: 4.7,
    cabinHeadroom: 1040,
    driverSeatHeightRange: { min: 580, max: 640 },
    roofHeight: 1675,
    steeringType: 'EPS',
    easeOfDriving: 'Very Easy',
    parkingDifficulty: 'Very Easy',
    idealHeightMin: 152,
    idealHeightMax: 195,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 3,
    safetyAgency: 'Global NCAP Rating',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=900&q=80',
    description: 'Iconic Tallboy design offering unmatched vertical headroom, sofa-like high seating position, huge 341L boot, and great city fuel economy.',
    baseScores: {
      safety: 5,
      groundClearance: 7,
      comfort: 8,
      spacePracticality: 9,
      mileageRunningCost: 10,
      maintenanceCost: 10,
      performance: 7,
      resaleValue: 9,
      highwayStability: 6,
      cityDriveSuitability: 10,
      ergonomicFit: 10,
      handleability: 10,
    },
    highlightBadges: ['Tallboy Headroom', '341L Large Boot', 'Effortless Ingress/Egress'],
    inherentStrengths: [
      'Huge 1040mm vertical headroom and upright seating make it exceptionally comfortable for tall drivers (6ft+)',
      'High hip-point allows effortless walk-in entry without crouching for elderly passengers',
      'Generous 341-litre boot easily handles large family luggage',
      'Super light controls and tight turning radius make it ideal for new drivers',
    ],
    inherentConsiderations: [
      'Tallboy vertical profile creates noticeable body roll in sharp high-speed highway corners',
      'Structural safety rating is modest (1-2 Star Global NCAP)',
      'Engine noise filters into cabin at higher highway RPMs',
    ],
    isActive: true,
  },
  {
    brand: 'Royal Enfield',
    model: 'Classic 350',
    category: 'Motorcycle',
    bodyType: 'Cruiser',
    variantSummary: 'Signals / Dark / Chrome 350',
    priceFrom: 1.93,
    priceTo: 2.30,
    priceDisplay: '₹ 1.93 - 2.30 Lakh*',
    fuelType: 'Petrol',
    transmission: '5-Speed Manual',
    engine: '349cc Air-Oil Cooled J-Series',
    engineCC: 349,
    power: '20.2 bhp',
    torque: '27 Nm @ 4000 rpm',
    mileage: '37.0 kmpl',
    mileageValue: 37.0,
    driveType: 'Chain',
    groundClearance: 170,
    seatingCapacity: 2,
    bootSpace: 0,
    seatHeight: 805,
    kerbWeight: 195,
    length: 2145,
    width: 785,
    height: 1090,
    wheelbase: 1390,
    turningRadius: 2.3,
    cabinHeadroom: 0,
    driverSeatHeightRange: { min: 805, max: 805 },
    roofHeight: 1090,
    steeringType: 'Manual',
    easeOfDriving: 'Moderate',
    parkingDifficulty: 'Moderate',
    idealHeightMin: 165,
    idealHeightMax: 196,
    bikeType: 'Cruiser',
    riderTriangle: 'Upright',
    seatToFootpegHeight: 440,
    handlebarReach: 650,
    beginnerFriendly: true,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 4,
    safetyAgency: 'Dual-Channel ABS',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=900&q=80',
    description: 'Timeless retro cruiser with iconic thump, heavy metal road stability, relaxed upright posture, and unmatched resale demand.',
    baseScores: {
      safety: 7,
      groundClearance: 7,
      comfort: 9,
      spacePracticality: 6,
      mileageRunningCost: 6,
      maintenanceCost: 7,
      performance: 7,
      resaleValue: 10,
      highwayStability: 9,
      cityDriveSuitability: 6,
      ergonomicFit: 9,
      handleability: 6,
    },
    highlightBadges: ['Iconic Retro Cruiser', 'Heavy High-Speed Poise', 'Top Resale Value'],
    inherentStrengths: [
      'Plush, wide sprung rider seat and relaxed upright ergonomics for long rides and tall riders',
      'Solid 195 kg metal build feels planted on crosswinds and highways',
      'Massive fan base and top-tier resale market value across India',
      'Smooth low-end torque allows relaxed cruising without frequent gear changes',
    ],
    inherentConsiderations: [
      'Heavy 195 kg kerb weight requires confidence and muscle in tight parking maneuvers',
      'Top-end speed is limited (~115 km/h) compared to modern sports bikes',
      'Seat height (805mm) combined with wide seat makes flat-footing difficult for riders under 5\'5"',
    ],
    isActive: true,
  },
  {
    brand: 'Yamaha',
    model: 'MT-15 V2',
    category: 'Motorcycle',
    bodyType: 'Naked Streetfighter',
    variantSummary: 'Deluxe | VVA Liquid Cooled',
    priceFrom: 1.68,
    priceTo: 1.74,
    priceDisplay: '₹ 1.68 - 1.74 Lakh*',
    fuelType: 'Petrol',
    transmission: '6-Speed with Assist & Slipper Clutch',
    engine: '155cc Liquid-Cooled 4V SOHC VVA',
    engineCC: 155,
    power: '18.4 bhp',
    torque: '14.1 Nm',
    mileage: '50.0 kmpl',
    mileageValue: 50.0,
    driveType: 'Chain',
    groundClearance: 175,
    seatingCapacity: 2,
    bootSpace: 0,
    seatHeight: 810,
    kerbWeight: 141,
    length: 2015,
    width: 800,
    height: 1070,
    wheelbase: 1325,
    turningRadius: 2.1,
    cabinHeadroom: 0,
    driverSeatHeightRange: { min: 810, max: 810 },
    roofHeight: 1070,
    steeringType: 'Manual',
    easeOfDriving: 'Easy',
    parkingDifficulty: 'Very Easy',
    idealHeightMin: 160,
    idealHeightMax: 185,
    bikeType: 'Streetfighter',
    riderTriangle: 'Sporty Forward',
    seatToFootpegHeight: 390,
    handlebarReach: 580,
    beginnerFriendly: true,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 4,
    safetyAgency: 'Dual-Channel ABS + Traction Control',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=900&q=80',
    description: 'Razor-sharp streetfighter with R15-derived liquid-cooled VVA engine, inverted USD front forks, traction control, and 50 kmpl efficiency.',
    baseScores: {
      safety: 8,
      groundClearance: 7,
      comfort: 7,
      spacePracticality: 5,
      mileageRunningCost: 9,
      maintenanceCost: 8,
      performance: 9,
      resaleValue: 8,
      highwayStability: 8,
      cityDriveSuitability: 10,
      ergonomicFit: 8,
      handleability: 9,
    },
    highlightBadges: ['50 kmpl Mileage', 'Traction Control + USD Forks', 'Agile City Carver'],
    inherentStrengths: [
      'Superb fuel economy (48-52 kmpl) despite class-leading sporty acceleration',
      'Ultra-light 141 kg weight and sharp chassis makes slicing through traffic effortless',
      'High-spec USD forks and standard Traction Control ensure superior grip',
      'Low maintenance costs with legendary Yamaha engine reliability',
    ],
    inherentConsiderations: [
      'Pillion seat is compact and unsuitable for long two-up journeys',
      'Firm rear suspension setup transmits sharp bumps on unpaved roads',
      'Tall riders over 6ft may find the sporty footpeg position slightly cramped on long rides',
    ],
    isActive: true,
  },
  {
    brand: 'Ather',
    model: '450X Gen 3',
    category: 'Scooter',
    bodyType: 'Electric Scooter',
    variantSummary: 'Pro Pack | 3.7 kWh',
    priceFrom: 1.40,
    priceTo: 1.55,
    priceDisplay: '₹ 1.40 - 1.55 Lakh*',
    fuelType: 'Electric',
    transmission: 'Automatic (Belt Drive)',
    engine: '6.4 kW PMSM Electric Motor',
    engineCC: 0,
    power: '8.58 bhp (6.4 kW)',
    torque: '26 Nm Instant',
    mileage: '150 km / charge (TrueRange 110km)',
    mileageValue: 35.0,
    driveType: 'Belt',
    groundClearance: 170,
    seatingCapacity: 2,
    bootSpace: 22,
    seatHeight: 780,
    kerbWeight: 111,
    length: 1891,
    width: 739,
    height: 1114,
    wheelbase: 1296,
    turningRadius: 1.9,
    cabinHeadroom: 0,
    driverSeatHeightRange: { min: 780, max: 780 },
    roofHeight: 1114,
    steeringType: 'Manual',
    easeOfDriving: 'Very Easy',
    parkingDifficulty: 'Very Easy',
    idealHeightMin: 152,
    idealHeightMax: 188,
    bikeType: 'Scooter',
    riderTriangle: 'Upright',
    seatToFootpegHeight: 410,
    handlebarReach: 560,
    beginnerFriendly: true,
    batteryCapacity: '3.7 kWh Lithium-ion IP67',
    chargingRequired: true,
    homeChargingTime: '5.5 hrs (Ather Dot)',
    fastChargingSupport: true,
    evRangeReal: 110,
    safetyRating: 5,
    safetyAgency: 'Combined Braking + AutoHold',
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=900&q=80',
    description: 'High-performance electric scooter with Google Maps touchscreen, Warp mode 0-40 in 3.3s, and zero maintenance belt drive.',
    baseScores: {
      safety: 8,
      groundClearance: 7,
      comfort: 8,
      spacePracticality: 7,
      mileageRunningCost: 10,
      maintenanceCost: 9,
      performance: 9,
      resaleValue: 7,
      highwayStability: 7,
      cityDriveSuitability: 10,
      ergonomicFit: 8,
      handleability: 10,
    },
    highlightBadges: ['Warp Mode 0-40 in 3.3s', 'Google Maps Touchscreen', '₹0.30/km Running Cost'],
    inherentStrengths: [
      'Instant 26 Nm torque makes city overtakes instantaneous and thrilling',
      'Negligible running cost (₹0.30 per km) with home charging',
      'Google Maps on-board touchscreen with Bluetooth call & music control',
      'Light balanced aluminum chassis handles quick turns with sportsbike stability',
    ],
    inherentConsiderations: [
      'Requires home 5A/15A socket or access to Ather Grid fast charger',
      'Not designed for inter-city long-distance highway touring (110km real range)',
      'Initial purchase price is higher than standard petrol 110cc scooters',
    ],
    isActive: true,
  },
  {
    brand: 'Honda',
    model: 'Activa 6G',
    category: 'Scooter',
    bodyType: 'Commuter Scooter',
    variantSummary: 'Standard / Deluxe / H-Smart',
    priceFrom: 0.76,
    priceTo: 0.83,
    priceDisplay: '₹ 76,000 - 83,000*',
    fuelType: 'Petrol',
    transmission: 'CVT Automatic (V-Matic)',
    engine: '109.51cc 4-Stroke SI Engine',
    engineCC: 110,
    power: '7.79 bhp',
    torque: '8.90 Nm',
    mileage: '55.0 kmpl',
    mileageValue: 55.0,
    driveType: 'Belt',
    groundClearance: 162,
    seatingCapacity: 2,
    bootSpace: 18,
    seatHeight: 765,
    kerbWeight: 106,
    length: 1833,
    width: 697,
    height: 1156,
    wheelbase: 1260,
    turningRadius: 1.8,
    cabinHeadroom: 0,
    driverSeatHeightRange: { min: 765, max: 765 },
    roofHeight: 1156,
    steeringType: 'Manual',
    easeOfDriving: 'Very Easy',
    parkingDifficulty: 'Very Easy',
    idealHeightMin: 148,
    idealHeightMax: 185,
    bikeType: 'Scooter',
    riderTriangle: 'Upright',
    seatToFootpegHeight: 400,
    handlebarReach: 540,
    beginnerFriendly: true,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 4,
    safetyAgency: 'Combi-Braking System (CBS)',
    image: 'https://images.unsplash.com/photo-1558981408-db0ecd8a1ee4?auto=format&fit=crop&w=900&q=80',
    description: 'India’s undisputed #1 family scooter offering bulletproof reliability, metal body panels, plush telescopic suspension, and unbeatable resale value.',
    baseScores: {
      safety: 7,
      groundClearance: 6,
      comfort: 9,
      spacePracticality: 8,
      mileageRunningCost: 9,
      maintenanceCost: 10,
      performance: 6,
      resaleValue: 10,
      highwayStability: 6,
      cityDriveSuitability: 10,
      ergonomicFit: 9,
      handleability: 10,
    },
    highlightBadges: ['India’s #1 Family Scooter', 'Bulletproof Reliability', 'All-Metal Body'],
    inherentStrengths: [
      'Extremely low maintenance costs with mechanics and parts available everywhere',
      'Comfortable 765mm low seat height is easily accessible for all family members & elders',
      'Durable full-metal body withstands tough daily city abuse',
      'Highest resale liquidity of any two-wheeler in the Indian market',
    ],
    inherentConsiderations: [
      'Top speed is around 80 km/h; not intended for highway touring',
      'Underseat storage (18L) does not fit large full-face helmets',
      'Modest drum brakes compared to modern disc setups',
    ],
    isActive: true,
  },
  {
    brand: 'TVS',
    model: 'Jupiter 125',
    category: 'Scooter',
    bodyType: 'Family Scooter',
    variantSummary: 'Disc / SmartXonnect',
    priceFrom: 0.86,
    priceTo: 0.97,
    priceDisplay: '₹ 86,000 - 97,000*',
    fuelType: 'Petrol',
    transmission: 'CVT Automatic',
    engine: '124.8cc ETFi Single Cylinder',
    engineCC: 125,
    power: '8.04 bhp',
    torque: '10.5 Nm',
    mileage: '50.0 kmpl',
    mileageValue: 50.0,
    driveType: 'Belt',
    groundClearance: 163,
    seatingCapacity: 2,
    bootSpace: 33,
    seatHeight: 765,
    kerbWeight: 108,
    length: 1852,
    width: 681,
    height: 1168,
    wheelbase: 1275,
    turningRadius: 1.85,
    cabinHeadroom: 0,
    driverSeatHeightRange: { min: 765, max: 765 },
    roofHeight: 1168,
    steeringType: 'Manual',
    easeOfDriving: 'Very Easy',
    parkingDifficulty: 'Very Easy',
    idealHeightMin: 148,
    idealHeightMax: 188,
    bikeType: 'Scooter',
    riderTriangle: 'Upright',
    seatToFootpegHeight: 420,
    handlebarReach: 550,
    beginnerFriendly: true,
    chargingRequired: false,
    homeChargingTime: '',
    fastChargingSupport: false,
    evRangeReal: 0,
    safetyRating: 4,
    safetyAgency: 'Synchronised Braking System',
    image: 'https://images.unsplash.com/photo-1558980394-0a06c4631733?auto=format&fit=crop&w=900&q=80',
    description: 'Practical family scooter with massive 33L underseat storage (fits 2 full helmets), external front fuel filler, and metal body.',
    baseScores: {
      safety: 7,
      groundClearance: 6,
      comfort: 9,
      spacePracticality: 10,
      mileageRunningCost: 8,
      maintenanceCost: 9,
      performance: 7,
      resaleValue: 8,
      highwayStability: 6,
      cityDriveSuitability: 10,
      ergonomicFit: 9,
      handleability: 10,
    },
    highlightBadges: ['33L Huge Storage (2 Helmets)', 'Front Fuel Filler', '125cc Peppy Engine'],
    inherentStrengths: [
      'Class-leading 33-litre underseat storage holds two full-face helmets',
      'Front external fuel filler cap means you never have to dismount to refuel',
      'Longest and most cushioned seat in the segment for rider and pillion',
      'Peppy 125cc engine easily pulls two adults on inclines',
    ],
    inherentConsiderations: [
      'Handling is tuned for comfort rather than aggressive sporty cornering',
      'Highway cruising above 85 km/h produces light handlebar vibration',
    ],
    isActive: true,
  }
];

module.exports = { seedVehicles };
